### ISSUE TITLE
bug: Store ips of the user in the db along with token, make sure token is valid for that ip

### ISSUE THREAD

**Issue by hkirat** [code100x/cms#1156]
If someone steals my jwt, they should not be able to access my dashboard
we should check if the ip is the same as the one they logged in with

**Comment by ItsFlash10** [comment]
on it

**Comment by farjad-akhan** [comment]
On it! #trying

**Comment by MeerUzairWasHere** [comment]
@hkirat We have to add model for IP, where we save all ips or just one more column in user table?
and we can stop him to login if ip are not same?

**Comment by NawinKumarSharma** [comment]
@hkirat , do we need to save ipAddress in session or userschema?

**Comment by devsargam** [comment]
@hkirat do we want this? really

**Comment by rishav-goswami** [comment]
> If someone steals my jwt, they should not be able to access my dashboard we should check if the ip is the same as the one they logged in with

Hey @hkirat and @devsargam ,

Instead of IP tracking we should use `http-only` cookies for `JWT `storing and its combination with `CORS`. Which can mitigate the mentioned issues of stealing `JWT` and accessing content. 

pov:- _In case if `JWT `is stolen even with this implementation then attacker is not able to access dashboard because he can't set the cookie to our origin, ultimately `CORS` will effect if he tries from other origin_

I can work on this If its resolves what you mentioned.
