### ISSUE TITLE
bug: admin dashboard unable to change urls

### ISSUE THREAD

**Issue by hkirat** [code100x/cms#1164]
Topbar hides the elements below
![Screenshot 2024-09-09 at 8 31 26 PM](https://github.com/user-attachments/assets/19ca1eb4-b267-4083-8915-6b2b61437bde)

**Comment by vekariaayush04** [comment]
@hkirat can you assign me this...

**Comment by keshav-exe** [comment]
fixing this @hkirat

**Comment by amanbairagi30** [comment]
@hkirat @devsargam 
How do you feel about these little tweaks in `design` , I don't know if this is needed or not but still did little revampification of `admin panel `  and also adding feature of `sending notification of discord`  (doing this again because my last PR(#601) was reviewed a bit but couldn't get merged on time hence a lot of conflicts)


![image](https://github.com/user-attachments/assets/e6beb786-fd4d-4a18-ab15-445ddb393cd3)
![image](https://github.com/user-attachments/assets/e256a3e7-7c36-4426-a01a-71c69aff525d)
![image](https://github.com/user-attachments/assets/62c98868-ebee-48a4-9c85-81eacfcc40dc)

few pages are also being revamped

**Comment by amanbairagi30** [comment]
> Is this for admin side? @amanbairagi30
> 
> Seems like a lot of people love it

Yes sir , for admin side

**Comment by devsargam** [comment]
@amanbairagi30 do u have a pr that is with latest changes

**Comment by amanbairagi89** [comment]
> @amanbairagi30 do u have a pr that is with latest changes

Raising it before EOD today

**Comment by amanbairagi30** [comment]
> @amanbairagi30 do u have a pr that is with latest changes

@devsargam will be raising it very shortly today
