### ISSUE TITLE
bug: Course Content on the sidebar overlaps with the contents when scrolled

### ISSUE THREAD

**Issue by SadatHussain7** [code100x/cms#1167]
**Describe the bug**
On the courses page when clicking the Show Contents button, the sidebar opens with the course contents. When it is scrolled the course contents overlap with the heading 'Course Content'

**To Reproduce**
1. On the courses page then click the Show Contents button and in the opened sidebar scroll
2. When it is scrolled the course contents overlap with the heading 'Course Content'

**Expected behavior**
Should not overlap

**Screenshots or GIFs**
![Screenshot from 2024-09-09 22-15-27](https://github.com/user-attachments/assets/6c6a851d-b222-4add-9f6d-cf205379fb7f)

**Info (please complete the following information):**

**Additional context**

**Comment by hxdy-1** [comment]
on it

**Comment by raghavsingh05** [comment]
Can we not add a background blur to this (example below
![Screenshot 2024-09-11 122809](https://github.com/user-attachments/assets/93f4eb39-4520-4063-bb33-9122c36091fa)
)

**Comment by ItsFlash10** [comment]
#1176 already has a fix for this

**Comment by AkshatJangid787** [comment]
I noticed this issue is still open, and I believe I can help resolve it. I’ve already implemented a fix that:

1. Ensures the sticky header has a solid background color so that the content hides underneath.
2. Adjusts the `z-index` to prevent the content from touching the header.
3. The solution works perfectly in both "light" and "dark modes".
4. I've also tested it across various screen sizes to ensure it’s responsive.

I would love to contribute to this project and I’m confident that my fix can resolve the issue. If possible, could you please assign this issue to me? I’m ready to submit a pull request.

![Screenshot_20240922_125638](https://github.com/user-attachments/assets/120c1582-a3cd-4523-bd0f-33a36717b974)
![Screenshot_20240922_125713](https://github.com/user-attachments/assets/269033ab-041f-4375-b7e9-32616b93b3cc)
![Screenshot_20240922_125727](https://github.com/user-attachments/assets/a6d4c5ca-9a75-4bfa-bc53-16e5a9402025)
![Screenshot_20240922_125757](https://github.com/user-attachments/assets/c7dfd220-5181-4147-a0f3-59ad0e6f051d)

Thanks a lot for your time and consideration!
