### ISSUE TITLE
bug: Fix the breaking UI in payout page

### ISSUE THREAD

**Issue by Parikshit2001** [code100x/cms#1215]
**Describe the bug**

**To Reproduce**
1. Start the project 
2. Go to the payout page

**Expected behavior**

**Screenshots or GIFs**
<img width="1710" alt="Screenshot 2024-09-14 at 9 49 53 PM" src="https://github.com/user-attachments/assets/072182de-8b5c-4793-aaa5-9922ebec902f">

**Info (please complete the following information):**
 - Brave
 - Version [v1.69.168]

**Additional context**

**Comment by Chaitanya-mittal** [comment]
What I have done
1. Added pt-8 (instead of pt-3) to the container containing the Payout Methods + Cards
2. Added my-8 (instead of my-2) and pt-8 to the container containing the Payout Methods Heading.
<img width="849" alt="Screenshot 2024-09-21 at 12 36 12 PM" src="https://github.com/user-attachments/assets/7290d526-ae81-4571-8ce6-2ccfb7211d99">


Screen shots
<img width="1088" alt="Screenshot 2024-09-21 at 12 36 29 PM" src="https://github.com/user-attachments/assets/8b1a842d-63e1-4daa-8fa4-15814fbe8276">
<img width="1088" alt="Screenshot 2024-09-21 at 12 36 41 PM" src="https://github.com/user-attachments/assets/ea54497e-b9f1-4980-9275-a30de8e70bd4">
<img width="1088" alt="Screenshot 2024-09-21 at 12 36 47 PM" src="https://github.com/user-attachments/assets/0bd4ef29-bdd7-4256-a1ec-0772059793ea">
