### ISSUE TITLE
bug: getting an error after running the command "pnpm run dev"

### ISSUE THREAD

**Issue by sudesh2** [code100x/cms#1233]
**Describe the bug**
after setting up for the first time i ran the command "pnpm run dev" i got this error --Error: EACCES: permission denied, unlink '/home/sdsh/Desktop/cms/.next/app-build-manifest.json'

![cms error](https://github.com/user-attachments/assets/4f855b59-8044-4266-b93a-23fb4eb05df2)

**Comment by sudesh2** [comment]
ran this command "sudo rm /home/sdsh/Desktop/cms/.next/app-build-manifest.json"   and  problem solved but i want to know why did i get this error . everyone facing this same error?

**Comment by dv8081** [comment]
You got the error because some files in the .next directory were created with root permissions (likely due to using sudo), causing permission conflicts. To avoid this, run development commands without sudo and ensure consistent file ownership. Do not use sudo for every command it is a bad habbit in linux distros. :)

**Comment by dv8081** [comment]
you got the error because some files in the .next directory were created with root permissions (likely due to using sudo), causing permission conflicts. to avoid this run development commands without sudo . donot use sudo with every command in linux it may break your system because you do not know what is in the scripts  if you know then go ahead :)
