### ISSUE TITLE
bug: Whole post page re-render when editor clicked

### ISSUE THREAD

**Issue by Zafeeruddin** [code100x/cms#1248]
**Describe the bug**
i) Re-rendering of page when reply button clicked on post page
ii) Re-rendering of page when editor is clicked.

**To Reproduce**
1. Go to questions tab, open a post.
2. Click on reply. //whole page gets re-rendered.
3. Click on editor //whole page gets re-rendered.
4. Try to vote //whole page gets re-rendered.

Ref:

https://github.com/user-attachments/assets/e0791afc-ad6c-48bd-b00e-aab9602f9518

**Comment by neehhaa06** [comment]
Hello  @Zafeeruddin :)

fix: #1248

`
Please, move state management for the editor, reply button, and voting to more specific components rather than the parent. Use `React.memo` to prevent unnecessary re-renders of child components. Additionally, optimize with `useCallback` and `useMemo` for functions and values that don't change frequently.
`

**Comment by Zafeeruddin** [comment]
Hey @neehhaa06 
Thanks for suggestions.
I revalidated post instead of whole question page in #1249 
This seems to work fine.
