### ISSUE TITLE
bug: Toast says `Comment upvoted` even when we remove upvote 

### ISSUE THREAD

**Issue by isrark005** [code100x/cms#1320]
**Describe the bug**
 Toast says `Comment upvoted` even when we remove upvote 

**To Reproduce**
1. upvote any comment 
2. remove your upvote
3. see error

**Screenshots or GIFs**
![image](https://github.com/user-attachments/assets/ab73dcae-0e5e-4c2c-8e4e-e8d3ae85acc4)

**Comment by iamhvsharma** [comment]
Assign me, I would love to work on this.

**Comment by SahilLamba0008** [comment]
Can I work on this issue ? #1320

**Comment by iamhvsharma** [comment]
I have solved this specific issue. 

Waiting for you to assign me. 

Adding the code snippet's to show my approach. 

Original Code 
![image](https://github.com/user-attachments/assets/fe1221c7-6756-49ec-b07d-99961a384ffb)

My Approach

![image](https://github.com/user-attachments/assets/b3c218bb-e48b-4467-a80c-0e41fc8c95f9)

Can you please assign me this issue so that I can submit a PR Request.

**Comment by iamhvsharma** [comment]
@hkirat No one is responding Sir :( 
Should I submit PR or not? 
I have fixed this particular bug

**Comment by devsargam** [comment]
This is done in https://github.com/code100x/cms/pull/1323

**Comment by devsargam** [comment]
@iamhvsharma you don't need to ask to create a pr. Just create it will be reviwed in few days

**Comment by iamhvsharma** [comment]
Oh, I didn't know! 
In the contributor's guidelines, it was mentioned that you should only submit a PR after the assigning.
