### ISSUE TITLE
bug: Multiple sessions

### ISSUE THREAD

**Issue by Munadil16** [code100x/cms#1517]
**Describe the bug**
I am able to login in 3-4 devices, and I'm not logged out for accessing content from more than 1 device/browser.

**To Reproduce**
1. Try logging in from 2 or more devices, you won't be logged out

**Expected behavior**
Earlier this wasn't the case, I was logged out from previous device/browser, if I access from more than 1 device/browser

**Comment by IkramBagban** [comment]
@devsargam please assign this to me.

**Comment by devsargam** [comment]
@IkramBagban how are you thinking of solving this?

**Comment by IkramBagban** [comment]
> @IkramBagban how are you thinking of solving this?

I am thinking to generate a unique JWT token on every login and store it in user's table. and validate the token on every request. and if the new login occurs then will replace the previous stored token with new token. this will solve the problem.

Btw what do you think? Should I store the token in the database, or should I use Redis to store the token since it would be faster?

**Comment by IkramBagban** [comment]
@devsargam done. Please check the pr #1520
