### ISSUE TITLE
bug: Unauthorized content and Non-Playable Videos Indexed in Search Results

### ISSUE THREAD

**Issue by Caien1** [code100x/cms#1543]
**Describe the bug**
In the search functionality on the website [app.100xdevs.com], videos that should be restricted to specific cohorts (e.g., Cohort 3.0 in my case) are visible in the search results even for users without access. Additionally, courses I do have access to (e.g., ML and Android) are indexed in search results , but they are not playable.

**To Reproduce**
1. Log into app.100xdevs.com.
2. Use the search bar to look for content related to Cohort 3.0 (in my case) or other restricted courses.
3. Observe that videos from Cohort 3.0 and unplayable videos for accessible courses (ML, Android) appear in the results.
**Expected behavior**
Restricted Content: Only videos for which the user has access should appear in search results.
Accessible Content: Search results should link to playable content for accessible courses without redirecting to unplayable pages.

**Screenshots or GIFs**
![image](https://github.com/user-attachments/assets/6eba31e4-5862-4b30-bd42-aa1ea8936c37)
[
![image](https://github.com/user-attachments/assets/d69d60a5-c51d-4ab0-81c5-fea1fffccaa8)
](url)

**Comment by vinayak20130** [comment]
Yes, the bug does occur because of sql query here cms\src\app\api\search\route.ts 
![pgadmin](https://github.com/user-attachments/assets/4f3c3f9a-5038-4b89-8b2e-b78333fbb3bd)
 now we need a query which would also check userId while searching now if userId is being saved somewhere we could directly insert it the file mentioned above if not changes will also have to be 
done in src\components\search\SearchBar.tsx  ------------ line 50 ---------- to also send user id
changing the existing sql query doesn't seem to be possible as it would either require atleast 2 join which would again be computationally expensive I would recommed a change in schema but that could lead to a snowball effect in other changes too
like filling a the new table when a use purchases new course and when a new course is added so apis corresponding to that will need to be changed do let me know as I am a fresher if my approach is correct

**Comment by abhirupPann** [comment]
where: {
    type: 'video',
    hidden: false,
  },
  
  as we are using "hidden:false" here, for this reason shouldn't we just get to watch the contents that we have purchased ?

**Comment by devsargam** [comment]
This will be very complicated to figure out since we don't keep the mapping for which cohort a user belongs to. I mean we do add it as a course but not exactly as a cohort so let's not make it complicated
