### ISSUE TITLE
Download pdf not working

### ISSUE THREAD

**Issue by hkirat** [code100x/cms#248]
<img width="1166" alt="Screenshot 2024-03-19 at 4 25 41 PM" src="https://github.com/code100x/cms/assets/8079861/ffe67e70-0cc6-41ee-99b6-c88db1d85fe8">
Seems like the download starts before the page is rendered

**Comment by devsargam** [comment]
hmmm, fair. Working when I integrated. Let's see if I can come to a conclustion

**Comment by shreyas0924** [comment]
This is from daily-code repo right?

**Comment by devsargam** [comment]
yep

**Comment by shreyas0924** [comment]
@devsargam Are you solving this issue?

**Comment by shreyas0924** [comment]
@hkirat Sometimes its working and sometimes its not working. 

![image](https://github.com/code100x/cms/assets/72003665/18dcd721-e8fb-4a41-8d39-900d0905866b)

**Comment by devsargam** [comment]
I am trying to figure it out. If u want u can do it as well. Idk what's going wrong. I can see the page is not rendering fast enough. Feel free to take this up

**Comment by vikasu16** [comment]
Hi @hkirat this issue is related to loading of data.
Your print method for pdf generation is being called before your page is even render properly that why it is not able to read the page content to create the pdf.
I tried to debug and solve the issue by letting the page to render properly and then print the content in pdf form.
![image](https://github.com/code100x/cms/assets/65640612/381c7510-ddec-421c-87ef-c24ee378b4a7)

Can you please assign this to me.

**Comment by devsargam** [comment]
@vikasu16, I was the person who was responsible for the pr that failed to do so. What was ur approach btw? Just wanted to know how u fixed it? 
Did u wait for the elements to render
Or 
Wait for certain time interval?

**Comment by vikasu16** [comment]
@devsargam to generate the pdf you need to have all the elements loaded on the page so the print function can read the html tags and make the pdf from it.
I just passed the condition to let the page load before it makes the pdf.

**Comment by vikasu16** [comment]
PR raised on daily code repo.
https://github.com/code100x/daily-code/pull/88
