### ISSUE TITLE
bug: UI of video page is cluttered

### ISSUE THREAD

**Issue by hkirat** [code100x/cms#313]
<img width="1355" alt="Screenshot 2024-04-02 at 4 24 58 AM" src="https://github.com/code100x/cms/assets/8079861/e7290524-b0a2-4bba-916e-a8d3aa3b9c50">

1. Sidebar is messed up
2. Buttons can be cleaner

**Comment by Pratham271** [comment]
Taking this up @hkirat

**Comment by mithun522** [comment]
Hey guys I am sorry to comment my doubt here. I dont know where i could go and ask thats why i am commenting it out here. Can only the members who have purchased the courses can contribute to this ?.

**Comment by Rimaru06** [comment]
@Pratham271  have you already fix this if not  i would also like to fix this

**Comment by Pratham271** [comment]
@Rimaru06 I have. Thanks for asking though

**Comment by Pratham271** [comment]
<img width="1710" alt="Screenshot 2024-04-02 at 3 49 54 PM" src="https://github.com/code100x/cms/assets/83640434/9f3cfe6d-a91a-4163-9ae0-340e48d1fe58">
<img width="1710" alt="Screenshot 2024-04-02 at 3 49 57 PM" src="https://github.com/code100x/cms/assets/83640434/c6f2bdea-2d1a-436f-b329-03de1da9a754">
<img width="1710" alt="Screenshot 2024-04-02 at 3 50 03 PM" src="https://github.com/code100x/cms/assets/83640434/0f48c963-012c-484b-bbaa-89106efb2824">

@hkirat bhaiya looks good to me. If there is any suggestion from your side I can make that change before generating a pr

**Comment by hkirat** [comment]
yup can merge

**Comment by Pratham271** [comment]
@hkirat made the pr please check

**Comment by visheshdubey** [comment]
Hi @hkirat, I have made a figma layout to de-clutter the video page, I have also considered adding some other UI/UX fixes. Please have a look. If it looks good to you, I can start working on this!

1.  I have moved back button from sidebar to the breadcrumbs
2. Instead of a fluid layout in main section, added a contained layout for better responsiveness on large screens.
3. Improved AppBar, and search input.
4. Other UI fixes.

![image 6](https://github.com/code100x/cms/assets/19987590/67bcbdc6-ce62-4845-a369-b37aa4e7b752)
![image 7](https://github.com/code100x/cms/assets/19987590/8b7e9252-a5a2-4c9b-8243-5746d1c583b4)
![image 8](https://github.com/code100x/cms/assets/19987590/684a3313-c44a-46dd-aff8-dcf1e608a3db)
 
Thanks
