### ISSUE TITLE
bug: On clicking View content it doesn't open

### ISSUE THREAD

**Issue by Abhijit-Jha** [code100x/cms#318]
**Describe the bug**
On clicking on the "View Content" button of Harnoor Android course and ML + MLOps course it redirects to https://harkirat.classx.co.in/ 
**To Reproduce**

**Expected behavior**
It should open the course content

**Screenshots or GIFs**
![image](https://github.com/code100x/cms/assets/118539047/d2f24bcc-d4f7-4eaf-aa8e-a79e3cd88cfb)
![image](https://github.com/code100x/cms/assets/118539047/2231b737-3d29-4452-968a-c5240f8f15d4)

 - Browser [e.g. chrome]

**Comment by t007rushi** [comment]
This bug I have also faced

@Abhijit-Jha For now you can go to [link](https://harkirat.classx.co.in/new-courses/8/content?activeTab=Content)
view content -> view details -> at last you would see both course

**Comment by Abhijit-Jha** [comment]
@t007rushi I perform the same steps you mentioned. Thanks.
but I thought it should be resolved, so I raised the issue.

**Comment by iamdarwinsai** [comment]
I don't thinks it's a bug, He just redirected it to the where we can actually view there videos. I guess for now only we can play Harkirat's videos in app.100xdevs.com

**Comment by SOUMITRO-SAHA** [comment]
While resolving this issue, I noticed that the videos from these two courses are not playable on the app.100xdevs.com video players. I suspect it's due to an authentication-related issue with `classx`, which redirects users to the `classx` website.

![image](https://github.com/code100x/cms/assets/68202064/851f1dda-eabf-4d61-a418-2515f83d9908)
![image](https://github.com/code100x/cms/assets/68202064/42965620-a4a5-4702-9051-127e219efbe3)


For now, you can follow these steps:
1. Visit https://harkirat.classx.co.in/
2. Navigate to your purchased course (select the course you purchased from the listed options).
3. Scroll down to find the courses.

**Comment by t007rushi** [comment]
Yes doing that only lastly @SOUMITRO-SAHA
