### ISSUE TITLE
Not able to change playback speed in firefox

### ISSUE THREAD

**Issue by joshihemal** [code100x/cms#35]
<img width="1181" alt="Screenshot 2024-02-02 at 6 54 49 AM" src="https://github.com/code100x/cms/assets/100120373/e2c9f7a0-992c-4f65-8858-a60339c571d0">

As shown in this image, when I have clicked on 1.5x its being selected 1x and 1.5x both and speed is not increasing to 1.5x

**Comment by Adiiittt** [comment]
I am Firefox user. The bug is not replicating on my machine. Maybe you should update your browser or clear the cache & then login again.

@hkirat maybe you could close this sir. Doesn't seem to be any issue. Thank You. 
![image](https://github.com/code100x/cms/assets/107144471/7206ecb4-02dd-41ec-bd31-7324d30c7871)

**Comment by joshihemal** [comment]
@Adiiittt the issue was i was using one extension called video speed controller which was overwriting it let me close the issue
