### ISSUE TITLE
Setup Error

### ISSUE THREAD

**Issue by Ameerjafar** [code100x/cms#524]
when setup the project npm run prisma:migrate:dev in not working instead npm run prisma:migrate is working and also in the package.json file in the script we didn't  mention prisma:migrate:dev we only mention prisma:migrate

![Screenshot 2024-05-04 082053](https://github.com/code100x/cms/assets/105500361/fe5b5375-046e-49ab-8636-0af3fb6214c6)

**Comment by mohakchakraborty2004** [comment]
the command `npm run prisma:migrate:dev` is the problem itself, its not the right the command line, since its missing in the script , I faced the problem in my machine as well , instead use `npm run prisma:migrate` .  It will work since it does exist on the scripts in package.json and the previous one doesn't. This should be updated in the readme as well. @hkirat dk if am right but this worked for me , and should work for everyone facing the problem. Do check it please.

**Comment by Anurag12133** [comment]
@Ameerjafar Broo if you need t setup the project read  the docs carefully and then make an issue
