### ISSUE TITLE
bug: Most videos are bookmarked, without explicitly being done.

### ISSUE THREAD

**Issue by Zafeeruddin** [code100x/cms#635]
**Describe the bug**
Videos till week-12 are bookmarked by default, and errors out if bookmark being removed
**To Reproduce**
1. Uncheck bookmarks, which are previously bookmarked 
2. See error

**Expected behavior**
Expected: 
a) No previous bookmarks, which I didn't do.
b) No error if uncheck it.
**Screenshots or GIFs**

![image](https://github.com/code100x/cms/assets/121102547/f9bd49c9-fdae-4acb-b63b-6f7dd9fed5a9)
Works fine for new bookmarks

**Comment by victorchrollo14** [comment]
This is a pretty weird bug. we can't reproduce it in development.
We could speculate why this error is happening.
1. There is no Bookmark data in the database
![image](https://github.com/code100x/cms/assets/89346667/7891c984-b2c4-412a-b4cc-696d16874eec)

 2.  but on the client side we are manual assigning some bookmark data like

```
{
    id: 5,
    userId: '1',
    contentId: 3,
    createdAt: new Date(),
}
```
3. when you click on bookMark button, the deleteBookmarkHandler gets triggered and tries to run the following code to delete the bookmark data from db. since you don't have a `bookmark` record with `id:5 and userId:'1' ` we are getting the prisma error.  

```
  const userId = session.user.id;
  const { id } = data;
  console.log(id);
  try {
    const deletedBookmark = await db.bookmark.delete({
      where: { id, userId },
    });
```

**Comment by victorchrollo14** [comment]
The only way to reproduce  this bug in dev  would be to modify the addedBookmark state with wrong data that doesn't exist in database.

! Not sure why this bug would appear in production, we'll probably have to look through the data in prod. Right now in dev we are using less example data and in production we have more data so maybe the the current code which works for a single data item, might be producing this bug, when used with a lot of data.
```
export const useBookmark = (bookmark: Bookmark | null, contentId: number) => {
  const newBookmark = {
    id: 5,
    userId: '1',
    contentId: 3,
    createdAt: new Date(),
  };
  const [addedBookmark, setAddedBookmark] = useState<Bookmark | null>(
    newBookmark,
  );

```
![Screenshot from 2024-05-15 11-17-34](https://github.com/code100x/cms/assets/89346667/6e459da5-f758-4f73-842c-6cb44b00b8c1)

**Comment by uttamsutariya** [comment]
Were you able to get the cause of this problem?
If you haven't started working on it, I can pick it up.

**Comment by victorchrollo14** [comment]
> Were you able to get the cause of this problem?
> If you haven't started working on it, I can pick it up.

I don't see this problem in development, it probably has something to do with the production database.

Go ahead and work on it, if you'd like to.

**Comment by uttamsutariya** [comment]
![image](https://github.com/code100x/cms/assets/81454473/863d8d86-683b-46fc-92e9-b8a6cc46b771)

So the issue here is even my `userId` is `40541`,  the server action fetches the bookmark with any userId (exists in db) as you can see in below screenshots.

![image](https://github.com/code100x/cms/assets/81454473/d8504fc7-3553-4056-bc5b-75102137ae51)
![image](https://github.com/code100x/cms/assets/81454473/4a8dfcb0-5acf-4036-a85e-925ee9120c95)
![image](https://github.com/code100x/cms/assets/81454473/75398fcc-918e-4ead-ad32-12df926f603f)
![image](https://github.com/code100x/cms/assets/81454473/215eb4e8-b598-48fb-bf08-073b8a0c0f83)

This is because there isn't any constraint while fetching all the contents.

![image](https://github.com/code100x/cms/assets/81454473/dae97e04-9039-4dc0-9c02-3b8007384b91)

There must be a constraint that makes sure we are fetching the bookmarks of the currently logged-in user only.

![image](https://github.com/code100x/cms/assets/81454473/e1d7f3aa-56cc-45a1-90f4-5cf5071c916b)

**Comment by victorchrollo14** [comment]
cool. nice job bro. 
Did you insert more data into the database to test it out?

**Comment by Prakhar788** [comment]
@uttamsutariya how did you found out that issue is with bookmark:true by adding more videos or by creating a diff user?

**Comment by uttamsutariya** [comment]
Initially, I didn't do anything in my local cms.

I saw the prisma error message, then I tried to see the network request to remove the bookmark. 

While doing this I saw that for each request the userId is not unique & not mine. So I felt that there is some issue with all the the fetched bookmarks.

Then I saw all the bookmarks have different different userId.
 
Now at that point I understood the problem that while fetching the content, the bookmarks are not being fetched of only mine, it's being fetched without any constraint of currently logged-in user.

So this way then I tried to create few users in my local db & resolved this issue.

So this kinda debugging skills you will eventually learn while working with prod databases & stuffs.

@hkirat Can you please review this PR as many people are struggling with the unexpected behaviour of bookmarks that they haven't added.
