### ISSUE TITLE
Bug: Watching video from Week 2 but button shows Week 01.

### ISSUE THREAD

**Issue by moteeullahazmi** [code100x/cms#752]
![Screenshot 2024-06-02 172310](https://github.com/code100x/cms/assets/61102569/ba11b769-35b1-4d8f-889d-d4cfbd72c9c5)

**Comment by JTiscodin** [comment]
This happens in every video, I was watching Week-11, it still shows Week-1 selected

The code where this bug is potentially happening is this part in SideBar.jsx, But there is no way to test it, because only one Course is available in the development db

![image](https://github.com/code100x/cms/assets/113091818/471a8343-9d25-4820-970d-24b29e4bcf60)
