### ISSUE TITLE
bug: Comment reply button   

### ISSUE THREAD

**Issue by Azzam1503** [code100x/cms#780]
Clicking on the reply button in the comment section of videos redirects to the home page.

**Comment by byte-king** [comment]
Issue seems to be in this part of code in Comments.tsx file: 
![image](https://github.com/code100x/cms/assets/55686016/2139f888-3bc2-43a2-b871-b4e84bae4500)
(Attaching image for reference)

**Comment by byte-king** [comment]
One solution could be to create a reply component which handles the replies. So that when the user clicks on reply icon/text, a new component is opened(similar to the public comment component) which gives user ability add a reply to the comment.

The reply component should have same properties as the comments component ( i.e. can be upvoted/downvoted and can also be replied further, creating a conversation chain)

![image](https://github.com/code100x/cms/assets/55686016/1d6a2a1b-c3a8-4da7-9bd8-01e4b1f70eb4)


Here, we will have to take care as to how will we be handling the comment text data behind the scenes.


Possible Solution:

![image](https://github.com/code100x/cms/assets/55686016/44be3a4d-452e-43a4-821b-fa72f3f9103d)

**Comment by Azzam1503** [comment]
so the reply button should act as a toggle for showing the reply comment component.

**Comment by byte-king** [comment]
Yes. Similar to how reddit comments work

**Comment by Chaitanya1672** [comment]
@Azzam1503 This issue is already fixed in PR #751 #742, if it is same issue you can close this issue.

**Comment by RahulMishra0722** [comment]
> @Azzam1503 This issue is already fixed in PR #751 #742, if it is same issue you can close this issue.

Stop gate keeping.

**Comment by Chaitanya1672** [comment]
> > @Azzam1503 This issue is already fixed in PR #751 #742, if it is same issue you can close this issue.
> 
> Stop gate keeping.

Ok Rahul
